[package]
name = "omnipoker"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix = "0.12"
actix-rt = "2.8"
actix-web-actors = "4.0"
env_logger = "0.10"
log = "0.4"
uuid = { version = "1.4", features = ["v4"] }
itertools = "0.10"